// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && ebpf

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tracerBioKey struct {
	_      structs.HostLayout
	Dev    uint32
	_      [4]byte
	Sector uint64
}

type tracerBioVal struct {
	_    structs.HostLayout
	Ts   uint64
	Cgid uint64
}

type tracerExecKey struct {
	_    structs.HostLayout
	Cgid uint64
	Comm [16]int8
}

type tracerOffcpuStart struct {
	_    structs.HostLayout
	Ts   uint64
	Cgid uint64
}

type tracerProcStat struct {
	_            structs.HostLayout
	Execs        uint64
	Exits        uint64
	ExitNonzero  uint64
	ExitSignaled uint64
	OomKills     uint64
	SigkillRcvd  uint64
	SigtermRcvd  uint64
	OffcpuNs     uint64
	IoLatUsSum   uint64
	IoCount      uint64
	IoLatUsMax   uint64
	LastSignal   uint32
	LastExitCode uint32
}

// loadTracer returns the embedded CollectionSpec for tracer.
func loadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracer: %w", err)
	}

	return spec, err
}

// loadTracerObjects loads tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracerObjects
//	*tracerPrograms
//	*tracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerSpecs struct {
	tracerProgramSpecs
	tracerMapSpecs
	tracerVariableSpecs
}

// tracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerProgramSpecs struct {
	HandleBlockComplete *ebpf.ProgramSpec `ebpf:"handle_block_complete"`
	HandleBlockIssue    *ebpf.ProgramSpec `ebpf:"handle_block_issue"`
	HandleExecve        *ebpf.ProgramSpec `ebpf:"handle_execve"`
	HandleExit          *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleOom           *ebpf.ProgramSpec `ebpf:"handle_oom"`
	HandleSchedSwitch   *ebpf.ProgramSpec `ebpf:"handle_sched_switch"`
	HandleSignal        *ebpf.ProgramSpec `ebpf:"handle_signal"`
}

// tracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerMapSpecs struct {
	ExecNames *ebpf.MapSpec `ebpf:"exec_names"`
	IoStart   *ebpf.MapSpec `ebpf:"io_start"`
	Offcpu    *ebpf.MapSpec `ebpf:"offcpu"`
	Stats     *ebpf.MapSpec `ebpf:"stats"`
}

// tracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerVariableSpecs struct {
	UnusedExecKey  *ebpf.VariableSpec `ebpf:"_unused_exec_key"`
	UnusedProcStat *ebpf.VariableSpec `ebpf:"_unused_proc_stat"`
}

// tracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
	tracerVariables
}

func (o *tracerObjects) Close() error {
	return _TracerClose(
		&o.tracerPrograms,
		&o.tracerMaps,
	)
}

// tracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerMaps struct {
	ExecNames *ebpf.Map `ebpf:"exec_names"`
	IoStart   *ebpf.Map `ebpf:"io_start"`
	Offcpu    *ebpf.Map `ebpf:"offcpu"`
	Stats     *ebpf.Map `ebpf:"stats"`
}

func (m *tracerMaps) Close() error {
	return _TracerClose(
		m.ExecNames,
		m.IoStart,
		m.Offcpu,
		m.Stats,
	)
}

// tracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerVariables struct {
	UnusedExecKey  *ebpf.Variable `ebpf:"_unused_exec_key"`
	UnusedProcStat *ebpf.Variable `ebpf:"_unused_proc_stat"`
}

// tracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerPrograms struct {
	HandleBlockComplete *ebpf.Program `ebpf:"handle_block_complete"`
	HandleBlockIssue    *ebpf.Program `ebpf:"handle_block_issue"`
	HandleExecve        *ebpf.Program `ebpf:"handle_execve"`
	HandleExit          *ebpf.Program `ebpf:"handle_exit"`
	HandleOom           *ebpf.Program `ebpf:"handle_oom"`
	HandleSchedSwitch   *ebpf.Program `ebpf:"handle_sched_switch"`
	HandleSignal        *ebpf.Program `ebpf:"handle_signal"`
}

func (p *tracerPrograms) Close() error {
	return _TracerClose(
		p.HandleBlockComplete,
		p.HandleBlockIssue,
		p.HandleExecve,
		p.HandleExit,
		p.HandleOom,
		p.HandleSchedSwitch,
		p.HandleSignal,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracer_bpfel.o
var _TracerBytes []byte
