//go:build ebpf

package ebpf

import (
	"bytes"
	"context"
	"encoding/binary"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"

	"github.com/genie-tooling/sysdiag-analyzer-go/internal/types"
)

// rawEvent matches `struct event` in bpf/tracer.c byte-for-byte (incl. tail pad).
type rawEvent struct {
	TsNs     uint64
	Pid      uint32
	Ppid     uint32
	CgroupID uint64
	ExitCode int32
	Kind     uint8
	Comm     [16]byte
	Filename [256]byte
	_        [3]byte
}

var unitSuffixes = []string{
	".service", ".scope", ".socket", ".target", ".mount", ".swap", ".slice", ".timer", ".path",
}

// Run loads the eBPF program, traces exec/exit for dur, and aggregates by unit.
func Run(ctx context.Context, dur time.Duration) *types.EBPFAnalysisResult {
	res := &types.EBPFAnalysisResult{UnitsWithExecs: map[string]int{}, UnitsWithExits: map[string]int{}}

	// On kernels >= 5.11 BPF uses memcg accounting, so removing the memlock
	// rlimit (which needs CAP_SYS_RESOURCE) is unnecessary. Ignore failure and
	// let a genuine privilege problem surface at load/attach with a clearer
	// message ("--enable-ebpf must run as root").
	_ = rlimit.RemoveMemlock()

	var objs tracerObjects // generated by bpf2go
	if err := loadTracerObjects(&objs, nil); err != nil {
		res.Error = "loading eBPF objects (needs root and a BTF-capable kernel): " + err.Error()
		return res
	}
	defer objs.Close()

	tpExec, err := link.Tracepoint("syscalls", "sys_enter_execve", objs.HandleExecve, nil)
	if err != nil {
		res.Error = "attaching execve tracepoint: " + err.Error()
		return res
	}
	defer tpExec.Close()
	tpExit, err := link.Tracepoint("sched", "sched_process_exit", objs.HandleExit, nil)
	if err != nil {
		res.Error = "attaching exit tracepoint: " + err.Error()
		return res
	}
	defer tpExit.Close()

	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		res.Error = "opening ring buffer: " + err.Error()
		return res
	}
	defer rd.Close()

	inode := buildCgroupInodeMap("/sys/fs/cgroup")
	ctx2, cancel := context.WithTimeout(ctx, dur)
	defer cancel()
	go func() { <-ctx2.Done(); rd.Close() }() // unblock Read on timeout

	for {
		rec, err := rd.Read()
		if err != nil {
			break
		}
		var e rawEvent
		if binary.Read(bytes.NewReader(rec.RawSample), binary.LittleEndian, &e) != nil {
			continue
		}
		unit := inode[e.CgroupID]
		if unit == "" {
			unit = fmt.Sprintf("cgroup:%d", e.CgroupID)
		}
		comm := cstr(e.Comm[:])
		if e.Kind == 0 {
			res.ExecEvents = append(res.ExecEvents, types.EBPFExecEvent{
				TimestampNs: e.TsNs, Pid: e.Pid, Ppid: e.Ppid, CgroupID: e.CgroupID,
				Comm: comm, Filename: cstr(e.Filename[:]), Argv: []string{},
			})
			res.UnitsWithExecs[unit]++
		} else {
			res.ExitEvents = append(res.ExitEvents, types.EBPFExitEvent{
				TimestampNs: e.TsNs, Pid: e.Pid, Ppid: e.Ppid, CgroupID: e.CgroupID,
				Comm: comm, ExitCode: e.ExitCode,
			})
			res.UnitsWithExits[unit]++
		}
	}
	return res
}

func cstr(b []byte) string {
	if i := bytes.IndexByte(b, 0); i >= 0 {
		b = b[:i]
	}
	return string(b)
}

// buildCgroupInodeMap maps cgroup directory inode -> owning systemd unit, so the
// kernel cgroup id from each event can be resolved to a unit name.
func buildCgroupInodeMap(base string) map[uint64]string {
	m := map[uint64]string{}
	_ = filepath.WalkDir(base, func(path string, d fs.DirEntry, err error) error {
		if err != nil || !d.IsDir() {
			return nil
		}
		info, err := os.Stat(path)
		if err != nil {
			return nil
		}
		st, ok := info.Sys().(*syscall.Stat_t)
		if !ok {
			return nil
		}
		if unit := deriveUnit(path, base); unit != "" {
			m[st.Ino] = unit
		}
		return nil
	})
	return m
}

func deriveUnit(path, base string) string {
	rel := strings.TrimPrefix(strings.TrimPrefix(path, base), "/")
	parts := strings.Split(rel, "/")
	for i := len(parts) - 1; i >= 0; i-- {
		for _, suf := range unitSuffixes {
			if strings.HasSuffix(parts[i], suf) {
				return parts[i]
			}
		}
	}
	return ""
}
