// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && ebpf

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tracerExecKey struct {
	_    structs.HostLayout
	Cgid uint64
	Comm [16]int8
}

type tracerProcStat struct {
	_            structs.HostLayout
	Execs        uint64
	Exits        uint64
	ExitNonzero  uint64
	ExitSignaled uint64
	OomKills     uint64
	SigkillRcvd  uint64
	SigtermRcvd  uint64
	LastSignal   uint32
	LastExitCode uint32
}

// loadTracer returns the embedded CollectionSpec for tracer.
func loadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracer: %w", err)
	}

	return spec, err
}

// loadTracerObjects loads tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracerObjects
//	*tracerPrograms
//	*tracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerSpecs struct {
	tracerProgramSpecs
	tracerMapSpecs
	tracerVariableSpecs
}

// tracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerProgramSpecs struct {
	HandleExecve *ebpf.ProgramSpec `ebpf:"handle_execve"`
	HandleExit   *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleOom    *ebpf.ProgramSpec `ebpf:"handle_oom"`
	HandleSignal *ebpf.ProgramSpec `ebpf:"handle_signal"`
}

// tracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerMapSpecs struct {
	ExecNames *ebpf.MapSpec `ebpf:"exec_names"`
	Stats     *ebpf.MapSpec `ebpf:"stats"`
}

// tracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerVariableSpecs struct {
	UnusedExecKey  *ebpf.VariableSpec `ebpf:"_unused_exec_key"`
	UnusedProcStat *ebpf.VariableSpec `ebpf:"_unused_proc_stat"`
}

// tracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
	tracerVariables
}

func (o *tracerObjects) Close() error {
	return _TracerClose(
		&o.tracerPrograms,
		&o.tracerMaps,
	)
}

// tracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerMaps struct {
	ExecNames *ebpf.Map `ebpf:"exec_names"`
	Stats     *ebpf.Map `ebpf:"stats"`
}

func (m *tracerMaps) Close() error {
	return _TracerClose(
		m.ExecNames,
		m.Stats,
	)
}

// tracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerVariables struct {
	UnusedExecKey  *ebpf.Variable `ebpf:"_unused_exec_key"`
	UnusedProcStat *ebpf.Variable `ebpf:"_unused_proc_stat"`
}

// tracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerPrograms struct {
	HandleExecve *ebpf.Program `ebpf:"handle_execve"`
	HandleExit   *ebpf.Program `ebpf:"handle_exit"`
	HandleOom    *ebpf.Program `ebpf:"handle_oom"`
	HandleSignal *ebpf.Program `ebpf:"handle_signal"`
}

func (p *tracerPrograms) Close() error {
	return _TracerClose(
		p.HandleExecve,
		p.HandleExit,
		p.HandleOom,
		p.HandleSignal,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracer_bpfeb.o
var _TracerBytes []byte
